name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Node Dependencies
        working-directory: ./web-ui
        run: pnpm install

      - name: Build WebUI
        working-directory: ./web-ui
        run: pnpm run build

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Prepare build files
        run: |
          # 就算没有密码，为了骗过 Gradle 校验，也必须写一个假的 local.properties
          echo "storeFile=debug.keystore" > local.properties
          echo "storePassword=android" >> local.properties
          echo "keyAlias=androiddebugkey" >> local.properties
          echo "keyPassword=android" >> local.properties
          
          # 创建一个空的 google-services.json 防止报错
          echo '{}' > app/google-services.json

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease -PbuildDir=build-release

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep -oP 'versionName\s*=\s*\"\K[^"]+' app/build.gradle.kts)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: artifacts
          path: app/build/outputs/apk/release/*.apk
